{{- $chartName := include "discrete-agent.name" . -}}
{{- $tracingUrl := include "discrete-agent.tracingUrl" . -}}
{{- $metricsUrl := include "discrete-agent.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  ROOT_DIR_NESTING_LEVEL: {{ .Values.env.watcher.rootDirNestingLevel | quote }}
  WATCH_DIRECTORY: {{ .Values.env.watcher.directory | quote }}
  WATCH_MIN_TRIGGER_DEPTH: {{ .Values.env.watcher.options.minTriggerDepth | quote }}
  WATCH_MAX_TRIGGER_DEPTH: {{ .Values.env.watcher.options.maxWatchDepth | quote }}
  WATCH_INTERVAL: {{ .Values.env.watcher.options.interval | quote }}
  WATCHER_SHP_RETRY_COUNT: {{ .Values.env.watcher.shpRetry.retries | quote }}
  WATCHER_SHP_RETRY_FACTOR: {{ .Values.env.watcher.shpRetry.factor | quote }}
  WATCHER_SHP_RETRY_MIN_TIMEOUT: {{ .Values.env.watcher.shpRetry.minTimeout | quote }}
  WATCHER_SHP_RETRY_MAX_TIMEOUT: {{ .Values.env.watcher.shpRetry.maxTimeout | quote }}
  WATCHER_SHP_RETRY_RANDOMIZE: {{ .Values.env.watcher.shpRetry.randomize | quote }}
  OVERSEER_URL: {{ .Values.rasterCommon.serviceUrls.discreteOverseer | quote }}
  AGENT_DB_URL: {{ .Values.rasterCommon.serviceUrls.discreteAgentDb | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  CLASSIFICATION_OPTIONS_STORAGE_PROVIDER: {{ .Values.env.classification.storageProvider | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
